<?php

use Illuminate\Database\Seeder;

class DimxdimTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\DimxDim::insert([
            [
              'dim_id'  => '1',
              'nim' => '111',
              'nama'          => 'Yon',
              'thn_masuk'      => '2017',
              'dari_jlh_anak'      => 'NULL',
              'penghasilan_ayah'      => 'NULL',
              'penghasilan_ayah_id'      => 'NULL',
              'penghasilan_ibu'      => 'NULL',
              'penghasilan_ibu_id'      => 'NULL',
              'pekerjaan_ayah_id'      => 'NULL',
              'keterangan_pekerjaan_ayah'      => 'NULL',
              'pekerjaan_ibu_id'      => 'NULL',
              'keterangan_pekerjaan_ibu'      => 'NULL',
            ],
            [
                'dim_id'  => '2',
                'nim' => '112',
                'nama'          => 'Ed',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '3',
                'nim' => '113',
                'nama'          => 'An',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '4',
                'nim' => '114',
                'nama'          => 'Wan',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '5',
                'nim' => '115',
                'nama'          => 'Den',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '6',
                'nim' => '116',
                'nama'          => 'Toni',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '7',
                'nim' => '117',
                'nama'          => 'Keni',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '8',
                'nim' => '118',
                'nama'          => 'Kai',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '9',
                'nim' => '119',
                'nama'          => 'Chan',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '10',
                'nim' => '120',
                'nama'          => 'Yeol',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '11',
                'nim' => '121',
                'nama'          => 'Baek',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '12',
                'nim' => '121',
                'nama'          => 'Do',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
              [
                'dim_id'  => '13',
                'nim' => '121',
                'nama'          => 'Adam',
                'thn_masuk'      => '2017',
                'dari_jlh_anak'      => 'NULL',
                'penghasilan_ayah'      => 'NULL',
                'penghasilan_ayah_id'      => 'NULL',
                'penghasilan_ibu'      => 'NULL',
                'penghasilan_ibu_id'      => 'NULL',
                'pekerjaan_ayah_id'      => 'NULL',
                'keterangan_pekerjaan_ayah'      => 'NULL',
                'pekerjaan_ibu_id'      => 'NULL',
                'keterangan_pekerjaan_ibu'      => 'NULL',
              ],
            
            
        ]);
    }
}
